name: PHPUnit

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['5.6', '7.0', '7.1', '7.2', '7.3']

    name: Test on ${{ matrix.os }} with php ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extension-csv: mbstring
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: PHP Unit tests
        run: php ./vendor/bin/phpunit --verbose
